version: '3.0'

services:
  frontend:
    image: minduc/pebble:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:80:3002
    env_file:
      - .env.frontend
  backend:
    image: minduc/pebble:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:8000:3000
    depends_on:
      - database
    env_file:
      - .env
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
