source 'https://rubygems.org'
ruby '~> 3.1.2'

gem 'rails', '~> 7.0.4.3'

gem 'active_storage_base64', '~> 2.0.0'
gem 'bootsnap', '~> 1.4', '>= 1.4.5'
gem 'jbuilder', '~> 2.10'
gem 'oj', '~> 3.9', '>= 3.9.2'
gem 'pg', '~> 1.1', '>= 1.1.4'
gem 'puma', '~> 5.6'
gem 'pundit', '~> 2.1'
gem 'rack-cors', '~> 1.0', '>= 1.0.6'
gem 'sendgrid', '~> 1.2.4'
gem "knock", github: "nsarno/knock", branch: "master",
    ref: "9214cd027422df8dc31eb67c60032fbbf8fc100b"
gem 'yt', '~> 0.32.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'
# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

group :development, :test do
  gem 'annotate', '~> 3.2', '>= 3.0.3'
  gem 'bullet', '~> 7.0.3'
  gem 'dotenv-rails', '~> 2.7.6'
  gem 'factory_bot_rails', '~> 5.1', '>= 5.1.1'
  gem 'pry-byebug', '~> 3.9', platform: :mri
  gem 'pry-rails', '~> 0.3.9'
  gem 'rspec_api_documentation', '~> 6.1.0'
  gem 'rspec-rails', '~> 4.1'
end

group :development do
  gem 'better_errors', '~> 2.5', '>= 2.5.1'
  gem 'brakeman', '~> 5.1'
  gem 'letter_opener', '~> 1.7'
  gem 'listen', '~> 3.2'
  gem 'rails_best_practices', '~> 1.20'
  gem 'reek', '~> 6.1', '>= 6.1.1'
  gem 'rubocop-rails', '~> 2.16', '>= 2.16.1', require: false
  gem 'rubocop-rootstrap', '~> 1.2'
  gem 'spring', '~> 4.0'
end

group :test do
  gem 'faker', '~> 2.13'
  gem 'shoulda-matchers', '~> 4.1', '>= 4.1.2'
  gem 'simplecov', '~> 0.13.0', require: false
  gem 'webmock', '~> 3.7', '>= 3.7.6'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
