export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const FETCH_VIDEOS_ACTION = 'FETCH_VIDEOS_ACTION';
export const ADD_VIDEO_ACTION = 'ADD_VIDEO_ACTION';
export const ADD_YOUTUBE_VIDEO_ACTION = 'ADD_YOUTUBE_VIDEO_ACTION';
