export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const FETCH_VIDEOS_ACTION = 'FETCH_VIDEOS_ACTION';
export const SHARE_VIDEO_ACTION = 'SHARE_VIDEO_ACTION';
